package usbharu.jmemo.memo;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

public class MemoCanvas {
	private JPanel contentPane;
	private JPanel mainCanvas;
	private JButton button1;
	private JButton button2;
	private JViewport viewport1;
	private JPanel canvasPanel;

	private Point pp = new Point();

	float scale = 0;

	public MemoCanvas() {
		PaintCanvas canvas = new PaintCanvas(500, 500);
		$$$setupUI$$$();
		canvasPanel.add(canvas);
		canvasPanel.addComponentListener(new ComponentAdapter() {
			/**
			 * Invoked when the component's size changes.
			 *
			 * @param e
			 */
			@Override
			public void componentResized(ComponentEvent e) {
				System.out.println(e);
				canvas.setSize(e.getComponent().getSize());
				System.out.println(canvas.getSize());
				canvas.repaint();
				canvas.revalidate();
			}
		});
	}

	public static void main(String[] args) {
		JFrame frame = new JFrame("MemoCanvas");
		frame.setContentPane(new MemoCanvas().contentPane);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.pack();
		frame.setVisible(true);
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		contentPane = new JPanel();
		contentPane.setLayout(new BorderLayout(0, 0));
		mainCanvas = new JPanel();
		mainCanvas.setLayout(new BorderLayout(0, 0));
		contentPane.add(mainCanvas, BorderLayout.CENTER);
		mainCanvas.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
		canvasPanel = new JPanel();
		canvasPanel.setLayout(new BorderLayout(0, 0));
		mainCanvas.add(canvasPanel, BorderLayout.CENTER);
		final JToolBar toolBar1 = new JToolBar();
		contentPane.add(toolBar1, BorderLayout.SOUTH);
		button1 = new JButton();
		button1.setText("Button");
		toolBar1.add(button1);
		button2 = new JButton();
		button2.setText("Button");
		toolBar1.add(button2);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return contentPane;
	}

}